version: '3.8'

services:
  db:
    container_name: ${POSTGRES_DB_CONTAINER_NAME}
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - ${POSTGRES_DB_HOST_PORT}:${POSTGRES_DB_HOST_PORT}
    volumes:
      - ./postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_DB_USER}" ]

  redis:
    container_name: ${REDIS_NAME}
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: bash -c 'uvicorn app.main:app --host ${APP_HOST} --port ${APP_HOST_PORT}'
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:${APP_HOST_PORT}
    restart: always
    env_file:
      - .env

  rabbitmq:
    container_name: ${RABBITMQ_CONTAINER_NAME}
    image: rabbitmq:latest
    hostname: ${RABBITMQ_HOST}
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 5

  celery:
    container_name: ${CELERY_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: [ "celery", "--app=src.app.background_tasks.tasks:synchronization", "worker", "-l", "INFO" ]
    depends_on:
      - app
